### ISSUE TITLE
Design prototype UI

### ISSUE THREAD

**Issue by kobryl** [LCBK/small-objects-counter#1]

**Comment by michalkr52** [comment]
I've provided some ideas on the [project's wiki](https://github.com/LCBK/small-objects-counter/wiki/Ideas)

**Comment by michalkr52** [comment]
I've drawn a simple sketch of the app's flow. It shows the two main screens the user will interact with, with their different functionalities.

This is neither a prototype nor a design, its purpose is to help understand/illustrate the UI.

![Image](https://github.com/LCBK/small-objects-counter/assets/46329932/4691527c-2d0f-4478-8e5f-6349eb5e527a)

**Comment by kobryl** [comment]
Looks good, let's start implementing first parts
